# This file generates the GitHub Actions matrix.
---
include:

  # sweep
  - board: nice_nano_v2
    shield: sweep_central_dongle nice_view_adapter dongle_display_view_pro_micro
    artifact-name: sweep_central_dongle
  - board: nice_nano_v2
    shield: sweep_central_left
    artifact-name: sweep_central_left
  - board: nice_nano_v2
    shield: sweep_peripheral_left
    artifact-name: sweep_peripheral_left
  - board: nice_nano_v2
    shield: sweep_peripheral_right
    artifact-name: sweep_peripheral_right

  # reset
  - board: nice_nano_v2
    shield: settings_reset
